web: node_modules/coffee-script/bin/coffee server/main.coffee
sync: node_modules/coffee-script/bin/cake sync:all
directory: node_modules/coffee-script/bin/cake sync:directory
wiki: node_modules/coffee-script/bin/cake sync:wiki
apis: node_modules/coffee-script/bin/cake sync:apis
twitter: node_modules/coffee-script/bin/cake sync:twitter
logos-original: node_modules/coffee-script/bin/cake logos:original
logos-open: node_modules/coffee-script/bin/cake logos:open
clean: node_modules/coffee-script/bin/cake clean
